import type { Metadata } from 'next'
import MyPageNav from '../user/_components/myPageNav'


export const metadata: Metadata = {
  title: '진또베이',
  description: 'Generated by create next app',
}

export default function MyLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
        <MyPageNav/>
        {children}  
    </div>
  )
}
